# Challenge - Joining on multiple tables
USE sakila;

-- Write SQL queries to perform the following tasks using the Sakila database:

-- List the number of films per category.
SELECT category_id, COUNT(*) AS num_films
FROM film_category
GROUP BY category_id;
-- Retrieve the store ID, city, and country for each store.
SELECT store_id, city FROM store AS s
JOIN address AS a
JOIN city AS c
ON s.address_id = a.address_id
AND a.city_id = c.city_id;

-- Calculate the total revenue generated by each store in dollars.

SELECT store_id, SUM(amount) AS total_revenue 
FROM store as st
JOIN staff as s
JOIN payment as p
ON s.store_id = st.store_id
AND p.staff_id = s.staff_id
GROUP BY store_id;

-- Determine the average running time of films for each category.
SELECT fc.category_id, AVG(f.length) AS avg_length
FROM film_category AS fc
JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY fc.category_id;

